# fly.toml app configuration file generated for phishing-dectector-api on 2025-10-05T02:28:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phishing-dectector-api'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
